{% set name = "vobject" %}
{% set version = "0.9.4" %}
{% set sha256 = "10b150b87ee5fffefd3aa1ea12f31aab45a7b7d010d1ce6816afaff8db726520" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - ics_diff = vobject.ics_diff:main
    - change_tz = vobject.change_tz:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-dateutil >=2.4.0

test:
  imports:
    - vobject

  commands:
    - ics_diff --help
    - change_tz --help

about:
  home: http://eventable.github.io/vobject/
  license: Apache
  license_family: Apache
  license_file: LICENSE-2.0.txt
  summary: 'A full-featured Python package for parsing and creating iCalendar and vCard files'
  dev_url: http://eventable.github.io/vobject/

extra:
  recipe-maintainers:
    - proinsias
