{% set name = "vobject" %}
{% set version = "0.9.5" %}
{% set md5 = "aa629d6ae95db5edfd5b2402eb1073cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - ics_diff = vobject.ics_diff:main
    - change_tz = vobject.change_tz:main

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - python-dateutil >=2.4.0

test:
  imports:
    - vobject

  commands:
    - ics_diff --help
    - change_tz --help

about:
  home: http://eventable.github.io/vobject/
  license: Apache
  license_family: Apache
  license_file: LICENSE-2.0.txt
  summary: 'A full-featured Python package for parsing and creating iCalendar and vCard files'
  dev_url: http://eventable.github.io/vobject/

extra:
  recipe-maintainers:
    - proinsias
